### ISSUE TITLE
关于cookie的疑问

### ISSUE THREAD

**Issue by longalong** [paperman0/duobaodao#1]
关于脚本里边cookie的处理，

{'code': 501, 'data': None, 'list': None, 'message': '用户未登录'}
程序结束

在填写cookie的时候，使用Chrome插件“edit this cookie”导出的cookie无法直接使用，尝试使用插件里边的trackid等的也失败了。请教，如何获得符合条件的cookie。

**Comment by openips** [comment]
使用正常 cookie取得不对
