### ISSUE TITLE
可以更新一下么？现在好些失效了。

### ISSUE THREAD

**Issue by ChenRuihua** [paperman0/duobaodao#3]
@Luck89757 可以更新一下么？现在好些失效了。非常感谢。

**Comment by Daman1213** [comment]
现在出价会出现以下报错：{'code': 555, 'data': None, 'list': None, 'message': '哎呀，出价超时了，请稍后再试'}

**Comment by Luck89757** [comment]
留个微信吧，我加你

在 2019年9月29日星期日，陈瑞华 <notifications@github.com> 写道：
